language: elixir
sudo: false
elixir: 1.4
notifications:
  recipients:
    - ben.wilson@cargosense.com
    - bruce.williams@cargosense.com
otp_release:
  - 19.2
script: "MIX_ENV=test mix local.hex --force && MIX_ENV=test mix do deps.get, test"
